In [17]:
import torch
import torchaudio
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

conformer = torchaudio.models.Conformer(
    input_dim=80,
    num_heads=4,
    ffn_dim=128,
    num_layers=4,
    depthwise_conv_kernel_size=31,
)

lengths = torch.randint(1, 400, (10,))  # (batch,)

input = torch.rand(10, int(lengths.max()), 80)  # (batch, num_frames, input_dim)
print(input.shape)
print(lengths)
output = conformer(input, lengths)
print(output[1])

torch.Size([10, 359, 80])
tensor([  5,  17, 255, 153, 211, 329, 359, 147, 177,  31])
tensor([  5,  17, 255, 153, 211, 329, 359, 147, 177,  31])


In [11]:
t = torch.empty(1, 3, 28, 28).fill_(32.)

length = torch.empty(32).fill_(128)
length

tensor([128., 128., 128., 128., 128., 128., 128., 128., 128., 128., 128., 128.,
        128., 128., 128., 128., 128., 128., 128., 128., 128., 128., 128., 128.,
        128., 128., 128., 128., 128., 128., 128., 128.])